apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/exercises-projets-pedagogiques/ldervode_IoT.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      enabled: true

