
Vagrant.configure("2") do |config|
  LOGIN = "ogokturk"
  IPS   = "192.168.56.110"
  BOX   = "bento/debian-13.0"

  config.vm.box = "#{BOX}"
  config.vm.hostname = "#{LOGIN}S"
  config.vm.network "private_network", ip: "#{IPS}"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "serverp2"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "./scripts/common.sh"
  config.vm.provision "shell", path: "./scripts/install_k3s_server.sh",
    args: ["#{IPS}"]
  config.vm.provision "shell", path: "scripts/apply_manifests.sh"
end
