Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  
  # Control Plane Node
  config.vm.define "k3s-master" do |master|
    master.vm.hostname = "k3s-master"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.synced_folder ".", "/vagrant", disabled: false
    
    master.vm.provider "virtualbox" do |v|
      v.name = "k3s-master"
      v.gui = false
      v.memory = "2048"  # More RAM for control plane
      v.cpus = 2
    end
    
    master.vm.provision "shell", path: "control.sh"
  end
  
  # Worker Node
  config.vm.define "k3s-worker" do |worker|
    worker.vm.hostname = "k3s-worker"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.synced_folder ".", "/vagrant", disabled: false
    
    worker.vm.provider "virtualbox" do |v|
      v.name = "k3s-worker"
      v.gui = false
      v.memory = "1024"
      v.cpus = 1
    end
    
    worker.vm.provision "shell", path: "agent.sh"
  end
end