
Vagrant.configure("2") do |config|
LOGIN = "ogokturk"
CLUSTER_TOKEN = "k3s-#{LOGIN}-cluster-default-token"
IPS   = "192.168.56.110"
IPSW  = "192.168.56.111"
BOX   = "bento/debian-13.0"

config.ssh.insert_key = false

config.vm.define "#{LOGIN}S" do |vm1|
vm1.vm.box = "#{BOX}"
vm1.vm.hostname = "#{LOGIN}S"
vm1.vm.network "private_network", ip: "#{IPS}"

vm1.vm.provider "virtualbox" do |vb|
  vb.name = "server"
  vb.memory = 2048
  vb.cpus = 2
end
vm1.vm.provision "shell", path: "./scripts/common.sh"
vm1.vm.provision "shell", path: "./scripts/install_k3s_server.sh",
      args: ["#{IPS}", "#{CLUSTER_TOKEN}"]
  end

  # Deuxième VM
  config.vm.define "#{LOGIN}SW" do |vm2|
    vm2.vm.box = "#{BOX}"
    vm2.vm.hostname = "#{LOGIN}SW"
    vm2.vm.network "private_network", ip: "#{IPSW}"

    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "serverWorker"
      vb.memory = 2048
      vb.cpus = 2
    end
  vm2.vm.provision "shell", path: "./scripts/common.sh"
  vm2.vm.provision "shell", path: "./scripts/install_k3s_agent.sh", args: ["#{IPS}", "#{IPSW}", "#{CLUSTER_TOKEN}"]
  end
end
